### ISSUE TITLE
Unable to build client

### ISSUE THREAD

**Issue by sdelamo** [grails-guides/grails-vue-combined#1]
```
cd intial $
initial $ ./gradlew client:build
:client:nodeSetup
:client:yarnSetup
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
/Users/sdelamo/Developer/grailsguides/grails-vue-combined/initial/client/.gradle/yarn/yarn-v1.3.2/bin/yarnpkg -> /Users/sdelamo/Developer/grailsguides/grails-vue-combined/initial/client/.gradle/yarn/yarn-v1.3.2/lib/node_modules/yarn/bin/yarn.js
/Users/sdelamo/Developer/grailsguides/grails-vue-combined/initial/client/.gradle/yarn/yarn-v1.3.2/bin/yarn -> /Users/sdelamo/Developer/grailsguides/grails-vue-combined/initial/client/.gradle/yarn/yarn-v1.3.2/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.3.2
added 1 package in 0.4s
:client:yarn
yarn install v1.3.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning jest-serializer-vue > pretty > js-beautify > editorconfig > @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
warning nightwatch > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "jest > jest-cli > jest-environment-jsdom > jsdom > request-promise-native@1.0.5" has unmet peer dependency "request@^2.34".
warning "jest > jest-cli > jest-environment-jsdom > jsdom > request-promise-native > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 20.73s.
:client:build
yarn run v1.3.2
$ node build/build.js
module.js:473
      throw err;
      ^

Error: Cannot find module '/Users/sdelamo/Developer/grailsguides/grails-vue-combined/initial/client/build/build.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
:client:build FAILED
```

**Comment by niravassar** [comment]
Ok let me try

**Comment by niravassar** [comment]
I tried and got this error. i made a checkin on Oct 3 that should resolve the issue, which i tried to checkout from scratch. it worked.
